services:
  laboratory-web-front:
    image: ghcr.io/avn-project/liccontrol-laboratory-front-end:latest
    container_name: laboratory-web-front
    command: [ "make", "run_production" ]
    volumes:
      - laboratory_frontend_dist:/laboratory/dist
    env_file:
      - ".env"
    networks:
      - license_control

volumes:
  laboratory_frontend_dist:

networks:
  license_control:
    name: license_control
    driver: bridge
    external: true
