services:
  my-laboratory-web-front:
    build: .
    container_name: my-laboratory-web-front
    command: ["make", "run"]
    ports:
      - "5173:5173"
    networks:
      - license_control

networks:
  license_control:
    driver: bridge
    name: license_control
