services:
  laboratory-web-front:
    image: ghcr.io/avn-project/liccontrol-laboratory-front-end:latest
    container_name: laboratory-web-front
    command: [ "make", "run_production" ]
    networks:
      - license_control

networks:
  license_control:
    name: license_control
    driver: bridge
    external: true
