# name: lint_format.yml

# on: [push, pull_request]

# jobs:
#   lint_and_test:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: '22'

#       - name: Install dependencies
#         run: npm install

#       - name: Run ESLint
#         run: npx eslint .

#       - name: Run Prettier
#         run: npx prettier --check .

#       - name: Run Stylelint
#         run: npx stylelint "**/*.{css,scss}" --allow-empty-input || true
